# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/a3w3ka2d796ghlhf31il839c0658m5ih-cmake-3.31.7/bin/cmake

# The command to remove a file.
RM = /nix/store/a3w3ka2d796ghlhf31il839c0658m5ih-cmake-3.31.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/donda/Documents/programming/cpp/brainfuck

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/donda/Documents/programming/cpp/brainfuck

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/a3w3ka2d796ghlhf31il839c0658m5ih-cmake-3.31.7/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/a3w3ka2d796ghlhf31il839c0658m5ih-cmake-3.31.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/donda/Documents/programming/cpp/brainfuck/CMakeFiles /home/donda/Documents/programming/cpp/brainfuck//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/donda/Documents/programming/cpp/brainfuck/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named brainfuck

# Build rule for target.
brainfuck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 brainfuck
.PHONY : brainfuck

# fast build rule for target.
brainfuck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/build
.PHONY : brainfuck/fast

src/eval.o: src/eval.cpp.o
.PHONY : src/eval.o

# target to build an object file
src/eval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/eval.cpp.o
.PHONY : src/eval.cpp.o

src/eval.i: src/eval.cpp.i
.PHONY : src/eval.i

# target to preprocess a source file
src/eval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/eval.cpp.i
.PHONY : src/eval.cpp.i

src/eval.s: src/eval.cpp.s
.PHONY : src/eval.s

# target to generate assembly for a file
src/eval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/eval.cpp.s
.PHONY : src/eval.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/reader.o: src/reader.cpp.o
.PHONY : src/reader.o

# target to build an object file
src/reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/reader.cpp.o
.PHONY : src/reader.cpp.o

src/reader.i: src/reader.cpp.i
.PHONY : src/reader.i

# target to preprocess a source file
src/reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/reader.cpp.i
.PHONY : src/reader.cpp.i

src/reader.s: src/reader.cpp.s
.PHONY : src/reader.s

# target to generate assembly for a file
src/reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainfuck.dir/build.make CMakeFiles/brainfuck.dir/src/reader.cpp.s
.PHONY : src/reader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... brainfuck"
	@echo "... src/eval.o"
	@echo "... src/eval.i"
	@echo "... src/eval.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/reader.o"
	@echo "... src/reader.i"
	@echo "... src/reader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

